name: Create Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Zip Repository
        run: |
          git archive --format zip --output worldyrotationretail.zip HEAD
      - name: Copy addon to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: ./worldyrotationretail.zip
          target: /usr/share/nginx/html/worldy/retail/
      - name: Get the version
        id: get_version
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Update version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: echo "${{ steps.get_version.outputs.TAG }}" > /usr/share/nginx/html/worldy/retail/.version
